services:
  - type: web
    name: wassl
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SSO_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
